Controllers films users
Anton-Phedorenko/java-filmorate pull request #1
Opened 2022-08-09 13:39 UTC by Anton-Phedorenko

2022-08-09 19:08 UTC, FanaticFiz requested changes
Финальный коммент на Я.Практикуме

2022-08-09 19:08 UTC, FanaticFiz commented on pom.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Салют!

`pom` файл желательно бы "причесать": очень не хватает отделения друг от друга (пустыми строками) глобальных частей таких как parent, `properties`, `dependencies`

Хорошим тоном будет указать кодировку в `properties`
`<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>`

2022-08-09 19:08 UTC, FanaticFiz commented on pom.xml
> +	<version>0.0.1-SNAPSHOT</version>
Советую прочитать про семантическое версионирование, ну а после, проставь более адекватную версию.

2022-08-09 19:08 UTC, FanaticFiz commented on pom.xml
> +			<artifactId>logbook-spring-boot-starter</artifactId>
Эта зависимость добавлена дважды

2022-08-09 19:08 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/FilmorateApplication.java
> +
Ну что это такое?
Где порядок? Что за неуместные пустые строки.

2022-08-09 19:08 UTC, FanaticFiz commented on src/main/resources/application.properties
> +logging.level.org.zalando.logbook=TRACE
Я буду топить за то чтобы ты сразу привыкал к написанию файла свойств для приложения в формате yaml -> application.yml

Соответственно - попрошу тебя этому следовать.
Как мини задание: посмотри как задавать порт для сервиса отличный от дефолтного и случайный.
(Сам порт менять не нужно, сломаются тесты)

2022-08-09 19:08 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/exceptions/ValidationException.java
> +package ru.yandex.practicum.filmorate.exceptions;
Следуй единому принципу именования пакетов. Определись во множественном числе или единственном тебе сейчас кажется более уместным. Но точно не в разнобой: `controller` / `exceptions`

2022-08-09 19:08 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/exceptions/ValidationException.java
> +public class ValidationException extends RuntimeException{
Сам эксепшн лучше переименовать, на BadRequestException поскольку в веб сервисе мы будет отвечать таким HTTP кодом на не каретные запросы, которые выявляет валидация.

2022-08-09 19:08 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/exceptions/ValidationException.java
> +}
Самих ексепшенов мало, он у тебя вообще один.
Не хватает как минимум ексепшена покрывающего случай если сущность не найдена

2022-08-09 19:08 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    Logger log = LoggerFactory.getLogger(FilmController.class);
Где модификаторы доступа?

2022-08-09 19:08 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public Film createFilm(@RequestBody Film film) {
Вот так будет лучше.

```
    @PostMapping(value = "/films")
    public Film createFilm(@RequestBody Film film) {
        if (filmNotValid(film)) {
            throw new ValidationException("Ошибка валидации при попытке добавить фильм");
        }
        
        film.setId(generateId());
        films.put(film.getId(), film);
        log.debug("Фильм " + film.getName() + " успешно добавлен");
        
        return film;
    }
```

Что изменилось?
- мы избавились от вложенности (else)
- мы явно в начале метода обозначили условия выхода
- мы инвертировали метод проверки(поскольку после рефакторинга он стал всегда использоваться с отрицанием) и подобрали удобочитаемое название

2022-08-09 19:08 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public boolean validateFilm(Film film) {
Этот метод построен неверно... зачем ему возвращать что то если ты везде внутри кидаешься ексепшенами?

Ты или уже возвращай true/false или назови метод согласно тому что он реально делает и не возвращай ничего...

2022-08-09 19:08 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private int generateId() {
ну можно же в одну строку )

2022-08-09 19:08 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +public class UserController {
Тут слиплось ВСЁ ! ))

Ну и для этого класса актуальны все замечания предыдущего контроллера

2022-08-09 19:08 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +            user.setName(user.getLogin());
Валидатор только валидирует. 
Логика формирования имени это бизнес логика/требование, не должно быть в валидаторе.

2022-08-09 19:08 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/models/Film.java
> +    public Film(int id, String name, String description, LocalDate releaseDate, int duration) {
- Такое кол-во конструкторов точно нужно?
- Навести порядок в классе - требования к code style никто не отменял

2022-08-09 19:08 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/models/Film.java
> +public class Film {
Я видел в pom валидатор, но нигде не увидел его применения.
Как так случилось?
Ты не разобрался в нём?

2022-08-09 19:08 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/models/User.java
> +public class User {
И еще ты не использовал `lombok`.
Мне то лично это нравиться, я считаю что вам сейчас ломбок только во вред идёт.
Так что я просто хотел спросить не возникло ли у тебя проблем с ним?

2022-08-11 19:07 UTC, Anton-Phedorenko commented on pom.xml
> +	<version>0.0.1-SNAPSHOT</version>
Версия 1.0.1 - потому что 1.0.0 должна была быть сразу -> 1.0.1 я пофиксил код. Минорную версию я не увеличивал, так как новую функциональность мы пока что не добавляли

2022-08-11 19:08 UTC, Anton-Phedorenko commented on src/main/java/ru/yandex/practicum/filmorate/exceptions/ValidationException.java
> +package ru.yandex.practicum.filmorate.exceptions;
Хорошо)

2022-08-11 19:09 UTC, Anton-Phedorenko commented on src/main/java/ru/yandex/practicum/filmorate/exceptions/ValidationException.java
> +}
Написал еще один эксепшн

2022-08-11 19:10 UTC, Anton-Phedorenko commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public Film createFilm(@RequestBody Film film) {
Выглядит красиво, в обоих классах написал таким вот образом

2022-08-11 19:11 UTC, Anton-Phedorenko commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public boolean validateFilm(Film film) {
я решил,что лучше возвращать true/false,потому что исключение выбросить я всегда успею,а логировать причину ошибки в методе могу,да и через if удобно проверять

2022-08-11 19:11 UTC, Anton-Phedorenko commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private int generateId() {
да,тут перемудрил я

2022-08-11 19:14 UTC, Anton-Phedorenko commented on src/main/java/ru/yandex/practicum/filmorate/models/User.java
> +public class User {
Я осознанно не использовал lombok. Когда проходил тренажер и делал задание в ide никаких сложностей с ним не было. Просто как то никто особо не хвалит эту библиотеку, и я к ней как то осторожно отношусь)

2022-08-11 19:15 UTC, Anton-Phedorenko commented on src/main/java/ru/yandex/practicum/filmorate/models/Film.java
> +    public Film(int id, String name, String description, LocalDate releaseDate, int duration) {
Такое количество конструкторов,как оказалось не нужно,а вот в классе User без пустого конструктора тесты в Postman не пропускают)

2022-08-11 19:16 UTC, Anton-Phedorenko commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +            user.setName(user.getLogin());
Хорошо)

2022-08-11 19:20 UTC, Anton-Phedorenko commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +public class UserController {
Code style вроде подкрутил )

2022-08-11 21:02 UTC, Anton-Phedorenko commented on src/main/resources/application.properties
> +logging.level.org.zalando.logbook=TRACE
Хорошо, я в файле application.yml закомментировал код,где изменил порт

2022-08-11 21:02 UTC, Anton-Phedorenko commented on src/main/java/ru/yandex/practicum/filmorate/exceptions/ValidationException.java
> +public class ValidationException extends RuntimeException{
Переименовал)

2022-08-11 21:30 UTC, Anton-Phedorenko commented on src/main/java/ru/yandex/practicum/filmorate/models/Film.java
> +public class Film {
Я добавил его, но в итоге не понял,мы делаем валидацию методом или валидатором?

2022-08-11 21:52 UTC, Anton-Phedorenko commented on pom.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Привет, файл pom.xml причесал вручную, settings->editor->code style->XML не нашел как отделять определенные секции друг от друга

2022-08-11 21:57 UTC, Anton-Phedorenko commented
Привет,Денис! Отправляю на проверку проект

2022-08-12 05:03 UTC, FanaticFiz commented on pom.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Да это нормально, этот файл не меняется часто

2022-08-12 05:28 UTC, FanaticFiz requested changes
Финальный комментарий на Я.Практикуме

2022-08-12 05:28 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/FilmorateApplication.java
> +import ru.yandex.practicum.filmorate.models.User;
Ты проигнорил/забыл про этот файл.

А тут помимо выравнивания кода еще и импорты надо вычистить!

2022-08-12 05:28 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public Film createFilm(@RequestBody Film film) {
Да, но ты упустил code style. Пустые строки были неспроста добавлены.
Валидацию отделили от основного кода
return тоже нужно отделять пустой строкой, это выход из метода он должен быть заметен.

2022-08-12 05:28 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public boolean filmNotValid(Film film) {
Поскольку это веб сервис, то сервер должен максимально информативно отвечать в чём именно ошибка. В каком поле и что по нашему мнению не так.
Иначе клиент не будет знать что ему исправить.

Поэтому, конечно, такая валидация не подойдет. 

Ну т.е. на этом этапе это не преграда для принятия ПР, но ты имей ввиду.

2022-08-12 05:28 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    private static final Logger log = LoggerFactory.getLogger(UserController.class);
`private static final Logger log` нет причины быть static!

2022-08-12 05:28 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/exception/NoSearchEntityException.java
> +public class NoSearchEntityException extends RuntimeException{
Обычно называют: `NotFoundException`

2022-08-12 05:28 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/models/Film.java
> +public class Film {
Та валидация покрывает стандартные кейсы и спасает нас от написания не нужного кода.
А в ручную мы дописываем например валидацию на дату релиза.

Советую добавить её использовать, ведь это частый кейс и тебе рано или поздно надо его освоить.

2022-08-12 05:30 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/models/Film.java
> +package ru.yandex.practicum.filmorate.models;
Название этого пакета выбивается: `models` -> `model`

2022-08-16 10:46 UTC, Anton-Phedorenko commented on src/main/java/ru/yandex/practicum/filmorate/FilmorateApplication.java
> +import ru.yandex.practicum.filmorate.models.User;
Теперь навел порядок

2022-08-16 10:47 UTC, Anton-Phedorenko commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public boolean filmNotValid(Film film) {
Я исправил на более информативное сообщение с конкретной датой

2022-08-16 10:53 UTC, Anton-Phedorenko commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    private static final Logger log = LoggerFactory.getLogger(UserController.class);
Не вопрос, я поменял,но почему то у нас в теории написано,далее цитирую:D

При объявлении логера принято использовать модификаторы private, static и final. Логер одинаков для всех экземпляров класса, поэтому можно сделать переменную статической, то есть создать один логер на класс. Также нет смысла менять экземпляр логера во время работы программы, поэтому переменную помечают final. Ну и чтобы логером класса нельзя было воспользоваться вне этого класса, переменная скрыта модификатором private.

2022-08-16 10:54 UTC, Anton-Phedorenko commented on src/main/java/ru/yandex/practicum/filmorate/exception/NoSearchEntityException.java
> +public class NoSearchEntityException extends RuntimeException{
Поменял название)

2022-08-16 10:54 UTC, Anton-Phedorenko commented on src/main/java/ru/yandex/practicum/filmorate/models/Film.java
> +package ru.yandex.practicum.filmorate.models;
Поменял

2022-08-16 11:32 UTC, Anton-Phedorenko commented
Привет,Денис! Отправляю проект на проверку

2022-08-16 12:08 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    private static final Logger log = LoggerFactory.getLogger(UserController.class);
Хороший вопрос!
Вот материал на тему https://www.slf4j.org/faq.html#declared_static

Основная мысль такая: в общем случае указание static несёт плюшки, когда у тебя много инстансов того класса в котором объявлен логер, Логер будет один на них всех. 
Но, внимание, у нас в веб приложении такого нет, все классы где ты добавляешь логер будут в одном экземпляре на всё приложение. Поэтому указание static и не несёт никаких плюшек.

2022-08-16 12:14 UTC, FanaticFiz approved these changes
Принимается

2022-08-16 12:14 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    Map<Integer, Film> films = new HashMap<>();
Нет модификатора доступа...

И отделяй переменные разного типа друг от друга пустой строкой.

2022-08-16 12:14 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public boolean filmNotValid(Film film) {
Да, но это твоё информативное сообщение было только в лог... а клиент его не увидит!

2022-09-05 09:32 UTC, merged